debug: false

site:
    name: Warehouse
    url: /

assets:
    url: /static/

database:
    migrations: "warehouse:migrations"

cache:
    browser: false
    varnish: false

paths:
    documentation: data/packagedocs

urls:
    documentation: "https://pythonhosted.org"
