language: python
python: 3.3
env:
    - TOXENV=py33
    - TOXENV=pep8
    - TOXENV=docs
    - TOXENV=packaging

install:
    # Upgrade PostgreSQL to 9.2
    - "if [[ $TOXENV == 'py33' ]]; then source /etc/lsb-release; fi"
    - "if [[ $TOXENV == 'py33' ]]; then sudo /etc/init.d/postgresql stop; fi"
    - "if [[ $TOXENV == 'py33' ]]; then sudo cp /etc/postgresql/9.1/main/pg_hba.conf ./; fi"
    - "if [[ $TOXENV == 'py33' ]]; then sudo apt-get remove postgresql postgresql-9.1 -qq --purge; fi"
    - "if [[ $TOXENV == 'py33' ]]; then echo \"deb http://apt.postgresql.org/pub/repos/apt/ $DISTRIB_CODENAME-pgdg main\" > pgdg.list; fi"
    - "if [[ $TOXENV == 'py33' ]]; then sudo mv pgdg.list /etc/apt/sources.list.d/; fi"
    - "if [[ $TOXENV == 'py33' ]]; then wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -; fi"
    - "if [[ $TOXENV == 'py33' ]]; then sudo apt-get update; fi"
    - "if [[ $TOXENV == 'py33' ]]; then sudo apt-get -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confnew' install postgresql-9.2 postgresql-contrib-9.2 -qq; fi"
    - "if [[ $TOXENV == 'py33' ]]; then sudo /etc/init.d/postgresql stop; fi"
    - "if [[ $TOXENV == 'py33' ]]; then sudo cp ./pg_hba.conf /etc/postgresql/9.2/main; fi"
    - "if [[ $TOXENV == 'py33' ]]; then sudo /etc/init.d/postgresql start; fi"
    # Install tox and coveralls
    - pip install tox coveralls

before_script:
    - psql -c "CREATE DATABASE warehouse ENCODING 'UTF8';" -U postgres

script:
    - WAREHOUSE_DATABASE_URL=postgresql://postgres@localhost/warehouse tox

after_success:
    - coveralls

branches:
    only:
        - master

notifications:
    irc:
        channels:
            - "irc.freenode.org#warehouse"
        use_notice: true
        skip_join: true
