language: python
python: 2.7
env:
    - TOXENV=py27
    - TOXENV=pypy
    - TOXENV=pep8
    - TOXENV=docs
    - TOXENV=packaging

install:
    # Upgrade PyPy
    - "[[ ${TOX_ENV} == pypy ]] && sudo add-apt-repository -y ppa:pypy/ppa || true"
    - "[[ ${TOX_ENV} == pypy ]] && sudo apt-get -y update && sudo apt-get -y install pypy || true"
    # This is required because we need to get rid of the Travis installed PyPy
    # or it'll take precedence over the PPA installed one.
    - "[[ ${TOX_ENV} == pypy ]] && sudo rm -rf /usr/local/pypy/bin || true"
    # Upgrade PostgreSQL to 9.2
    - source /etc/lsb-release
    - sudo /etc/init.d/postgresql stop
    - sudo cp /etc/postgresql/9.1/main/pg_hba.conf ./
    - sudo apt-get remove postgresql postgresql-9.1 -qq --purge
    - echo "deb http://apt.postgresql.org/pub/repos/apt/ $DISTRIB_CODENAME-pgdg main" > pgdg.list
    - sudo mv pgdg.list /etc/apt/sources.list.d/
    - wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confnew' install postgresql-9.2 postgresql-contrib-9.2 -qq
    - sudo /etc/init.d/postgresql stop
    - sudo cp ./pg_hba.conf /etc/postgresql/9.2/main
    - sudo /etc/init.d/postgresql start
    # Install tox and coveralls
    - pip install tox coveralls

before_script:
    - psql -c "CREATE DATABASE warehouse ENCODING 'UTF8';" -U postgres

script:
    - WAREHOUSE_DATABASE_URL=postgresql://postgres@localhost/warehouse tox

after_success:
    - coveralls

branches:
    only:
        - master

notifications:
    irc:
        channels:
            - "irc.freenode.org#warehouse"
        use_notice: true
        skip_join: true
