language: python
python: 2.7

addons:
  postgresql: 9.3

env:
    global:
        - WAREHOUSE_DATABASE_URL=postgresql://postgres@localhost/warehouse
        - secure: "gf4gNhmaicVY8/6OTZZcc8TCtIpZO58M0N+vAdT/KmsMBOxZY6PakuMQV8DmDfWskSImQQXdaLGE+Um5KanXsPvE4MyaZ7VpRTd7xJ646uoNdFcmMPKasdR8xz+k5ioTbZ4i2iSxgXhMixaEt1aiT7JsaKHhAmOSVltAp4IW8Bg="
    matrix:
        - TOXENV=py27
        - TOXENV=pypy
        - TOXENV=pep8
        - TOXENV=docs
        - TOXENV=packaging

install:
    - pip install tox

before_script:
    - psql --version
    - psql -c "CREATE DATABASE warehouse ENCODING 'UTF8';" -U postgres

script:
    - tox

after_success:
    - "if [[ $TRAVIS_BRANCH == 'master' ]] && [[ $TOXENV == 'pypy' ]]; then curl $WAREHOUSE_DEPLOY_URL > /dev/null 2>&1; fi"

branches:
    only:
        - master

notifications:
    irc:
        channels:
            - "irc.freenode.org#warehouse"
        use_notice: true
        skip_join: true
