debug: true

site:
    name: Warehouse (dev)

assets:
    directory: "static"

database:
    url: "postgresql://localhost/warehouse"

redis:
    url: "redis://localhost:6379/0"

paths:
    packages: "data/packages"

cache:
    browser:
        simple: 1
        packages: 1
        project_detail: 1
    varnish:
        simple: 120
        packages: 120
        project_detail: 120

fastly: true
